### ISSUE TITLE
command 'type' already exists

### ISSUE THREAD

**Issue by bpanmit** [ArturoDent/jump-and-select#4]
After installation, when i pressed either the keyboard shortcut or used the command, it says `command 'type' already exists`

`Command 'Jump-Select: Jump forward to next occurrence' resulted in an error (command 'type' already exists)`

Could you help me to fix this issue?

**Comment by ArturoDent** [comment]
Unfortunately, this issue cannot be fixed.  It means you have another extension that also uses the `type` command - vim and neovim and others do so.  And only the last extension to register `type`  that gets loaded when the extension host starts up can use it.

See [Multiple extensions registering the 'type' command](https://github.com/Microsoft/vscode/issues/13441)

> We added registerCommand("type") especially to enable vim mode to be implemented from an extension. We didn't want to bake vim mode in the core, and there can be only one handler. We never considered typing being something collaborative (in this case between vscode-jumpy and VSCodeVim). Today, the last one wins.

**Comment by digitalmaster** [comment]
> hi! how can i know which other extension is using that `type` command? i have installed several of vim-like extensions, but i have disabled _all_ of them; so...

I'm trying to figure this same thing. I already uninstalled the ones mentioned.

**Comment by ArturoDent** [comment]
You can try the command `Help: Start Extension Bisect` and report the results.

The command will walk through bisecting your installed extensions where you should test this extension's keybindings at each step to see if the problem still exists.  Hopefully, you get to another extension that is also registering the `type` command.  

But if you still have the problem after disabling ALL your extensions then the bisect might do no good.

I note the issue I mentioned above is still open since 2016...

**Comment by ArturoDent** [comment]
Yes, please create a new issue for the `(` bug.
