### ISSUE TITLE
Some characters don't work `(` or `[` or `.`

### ISSUE THREAD

**Issue by digitalmaster** [ArturoDent/jump-and-select#6]
For some reason some characters don't work.

I was trying to record a video showing the issue, but hard to see since the final keystroke is captured somehow and doesn't show up on screen. In all the cases where it looks like nothing happened i'm basically hitting of the characters mentioned in title

I've checked to make sure that nothing else is mapped to those keys.

https://github.com/ArturoDent/jump-and-select/assets/1279335/1ae47483-1deb-4f50-b16c-731e068077fc

Thanks for taking a look 🙏🏽

**Comment by ArturoDent** [comment]
Thanks for finding this bug.  It is because those are characters used in regular expressions.  v0.5.0 of this extension (just published) should fix this issue.

 I removed the ability to use regular expressions in keybindings to simplify the process but may consider adding that functionality back.  But it probably involves another setting for a regex flag which I would rather not do unless a number of people want the ability to put a regex into a keybinding.

Let me know if the fix works for you.  Thanks.
